/**
 * Master Hero Records Definition
 * Exact IDs, names, and parameters defined in DATA_SPEC.md Section 3.
 * All generators import from here to guarantee cross-file consistency.
 */

import { User, Proposal, ChangeEvent, DriftFlag, RepNote } from '../src/types';

export const HERO_USERS: User[] = [
  {
    user_id: 'USR-001',
    name: 'Elena Marsh',
    persona_id: 'P1',
    market_code: 'ALL',
    territory_id: null,
    agency_name: null,
  },
  {
    user_id: 'USR-002',
    name: 'Jonas Weber',
    persona_id: 'P2',
    market_code: 'MKT_B',
    territory_id: null,
    agency_name: null,
  },
  {
    user_id: 'USR-003',
    name: 'Sofia Lindqvist',
    persona_id: 'P2',
    market_code: 'MKT_A',
    territory_id: null,
    agency_name: null,
  },
  {
    user_id: 'USR-004',
    name: 'Arif Santoso',
    persona_id: 'P2',
    market_code: 'MKT_C',
    territory_id: null,
    agency_name: null,
  },
  {
    user_id: 'USR-005',
    name: 'Priya Raman',
    persona_id: 'P3',
    market_code: 'MKT_B',
    territory_id: null,
    agency_name: null,
  },
  {
    user_id: 'USR-006',
    name: 'Tomás Ferreira',
    persona_id: 'P4',
    market_code: 'MKT_B',
    territory_id: 'TER-B-03',
    agency_name: null,
  },
  {
    user_id: 'USR-007',
    name: 'Dewi Kartika',
    persona_id: 'P5',
    market_code: 'MKT_C',
    territory_id: null,
    agency_name: 'Northbay Field Research',
  },
  {
    user_id: 'USR-008',
    name: 'Catherine Doyle',
    persona_id: 'P6',
    market_code: 'ALL',
    territory_id: null,
    agency_name: null,
  },
  {
    user_id: 'USR-009',
    name: 'Marcus Okafor',
    persona_id: 'P6',
    market_code: 'ALL',
    territory_id: null,
    agency_name: null,
  },
];

export const HERO_ACCOUNT_B001 = {
  hco_id: 'ACC-B-001',
  market_code: 'MKT_B' as const,
  name: 'St. Aldric University Hospital',
  archetype: 'Integrated network',
  hco_type: 'IDN' as const,
  region: 'North',
  urbanicity: 'Urban' as const,
  beds: 850,
  annual_patient_volume_ta: {
    AUR: 1420,
    ZEN: 860,
    CRD: 3200,
    NEU: 680,
    BRV: 1100,
  },
  affiliated_hcp_count: 6,
  kam_user_id: 'USR-005',
  procurement_model: 'Central tender' as const,
  treatment_capability: 'Full (infusion + specialist)',
  decision_model: 'Committee-led',
};

export const HERO_HCP_B0001 = {
  hcp_id: 'HCP-B-0001',
  market_code: 'MKT_B' as const,
  first_name: 'Hanna',
  last_name: 'Vogel',
  display_name: 'Dr. Hanna Vogel',
  hcp_type: 'Specialist' as const,
  specialty: 'Dermatology',
  years_in_practice: 14,
  gender: 'F' as const,
  region: 'North',
  urbanicity: 'Urban' as const,
  practice_type: 'Hospital' as const,
  territory_id: 'TER-B-03',
  brick_id: 'BRK-B-014',
  primary_hco_id: 'ACC-B-001',
  rep_user_id: 'USR-006',
  kol_flag: true,
  in_customer_master: true,
  created_date: '2023-01-15',
};

export const HERO_NOTE_000001: RepNote = {
  note_id: 'NOTE-000001',
  market_code: 'MKT_B',
  hcp_id: 'HCP-B-0001',
  hco_id: 'ACC-B-001',
  rep_user_id: 'USR-006',
  date: '2026-10-10',
  brand_code: 'AUR',
  text: 'Dr. Vogel has started 4 new moderate-to-severe psoriasis patients on Aurelix since August and asked for the patient support programme materials. Prefers to receive updates through the portal rather than in-person visits.',
  ai_extracted: true,
  extracted_signals: [
    {
      dimension_code: 'ADOPTION',
      direction: 'Up',
      proposed_value: 'Expansion',
      evidence_quote: 'started 4 new moderate-to-severe psoriasis patients on Aurelix since August',
      confidence: 'High',
    },
    {
      dimension_code: 'DIGITAL',
      direction: 'Up',
      proposed_value: 'Savvy',
      evidence_quote: 'Prefers to receive updates through the portal rather than in-person visits',
      confidence: 'Medium',
    },
    {
      dimension_code: 'CHANNEL_PREF',
      direction: 'None',
      proposed_value: 'Portal',
      evidence_quote: 'Prefers to receive updates through the portal',
      confidence: 'Medium',
    },
  ],
};

export const HERO_EVENTS_HCP_B0001: ChangeEvent[] = [
  {
    event_id: 'EVT-000001',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    signal_type: 'Sales trend',
    source_category: 'Sales',
    detected_by: 'Agent',
    detected_at: '2026-10-02T08:15:00Z',
    magnitude: '+12% QoQ brick volume (BRK-B-014)',
    direction: 'Up',
    description: 'Brick-level sales in BRK-B-014 grew 12% in Q3 2026 vs Q2 2026.',
    data_age_days: 13,
    led_to_drift_flag: true,
  },
  {
    event_id: 'EVT-000002',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    signal_type: 'Digital engagement',
    source_category: 'Digital',
    detected_by: 'Agent',
    detected_at: '2026-10-05T14:30:00Z',
    magnitude: 'Portal visits 3 → 6/mo',
    direction: 'Up',
    description: 'Portal session frequency doubled over the last 3 months with 6 sessions in Sep 2026.',
    data_age_days: 10,
    led_to_drift_flag: true,
  },
  {
    event_id: 'EVT-000003',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    signal_type: 'PMR wave',
    source_category: 'Survey',
    detected_by: 'Agent',
    detected_at: '2026-10-07T09:00:00Z',
    magnitude: 'Late majority → Early adopter',
    direction: 'Up',
    description: 'PMR 2026-W2 response recorded Dr. Vogel in the Early Adopter attitudinal cluster.',
    data_age_days: 8,
    led_to_drift_flag: true,
  },
  {
    event_id: 'EVT-000004',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    signal_type: 'Rep note',
    source_category: 'CRM',
    detected_by: 'GenAI',
    detected_at: '2026-10-10T16:45:00Z',
    magnitude: 'Adoption Expansion + Digital Savvy',
    direction: 'Up',
    description: 'Rep Tomás Ferreira logged 4 new patient starts and portal preference.',
    data_age_days: 5,
    led_to_drift_flag: true,
  },
];

export const HERO_FLAGS_HCP_B0001: DriftFlag[] = [
  {
    flag_id: 'DRF-000001',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    dimension_code: 'SEGMENT',
    current_value: 'B',
    indicated_value: 'A',
    drift_score: 0.88,
    confidence: 'High',
    threshold_ref: 'THR-B-SEG-01',
    supporting_event_ids: ['EVT-000001', 'EVT-000002', 'EVT-000003', 'EVT-000004'],
    independent_signal_count: 4,
    model_version: 'v2.4-drift-classifier',
    flagged_at: '2026-10-11T09:00:00Z',
  },
  {
    flag_id: 'DRF-000002',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    dimension_code: 'BEHAVIOURAL',
    current_value: 'Traditionalist',
    indicated_value: 'Engaged',
    drift_score: 0.82,
    confidence: 'High',
    threshold_ref: 'THR-B-BEH-01',
    supporting_event_ids: ['EVT-000001', 'EVT-000002'],
    independent_signal_count: 2,
    model_version: 'v2.4-drift-classifier',
    flagged_at: '2026-10-11T09:05:00Z',
  },
  {
    flag_id: 'DRF-000003',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    dimension_code: 'ATTITUDINAL',
    current_value: 'Late majority',
    indicated_value: 'Early adopter',
    drift_score: 0.95,
    confidence: 'High',
    threshold_ref: 'THR-B-ATT-01',
    supporting_event_ids: ['EVT-000003'],
    independent_signal_count: 1,
    model_version: 'v2.4-drift-classifier',
    flagged_at: '2026-10-11T09:10:00Z',
  },
  {
    flag_id: 'DRF-000004',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    dimension_code: 'DIGITAL',
    current_value: 'Evolving',
    indicated_value: 'Savvy',
    drift_score: 0.85,
    confidence: 'High',
    threshold_ref: 'THR-B-DIG-01',
    supporting_event_ids: ['EVT-000002', 'EVT-000004'],
    independent_signal_count: 2,
    model_version: 'v2.4-drift-classifier',
    flagged_at: '2026-10-11T09:15:00Z',
  },
  {
    flag_id: 'DRF-000005',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    dimension_code: 'ADOPTION',
    current_value: 'Consideration',
    indicated_value: 'Expansion',
    drift_score: 0.91,
    confidence: 'High',
    threshold_ref: 'THR-B-ADP-01',
    supporting_event_ids: ['EVT-000001', 'EVT-000004'],
    independent_signal_count: 2,
    model_version: 'v2.4-drift-classifier',
    flagged_at: '2026-10-11T09:20:00Z',
  },
];

export const HERO_PROPOSALS_HCP_B0001: Proposal[] = [
  {
    proposal_id: 'PRP-000001',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    indication_code: 'AUR_PSO',
    dimension_code: 'SEGMENT',
    current_value: 'B',
    proposed_value: 'A',
    segment_age_days: 164,
    confidence: 'High',
    drivers: [
      { label: 'Brick-level Aurelix sales (BRK-B-014)', value: '+12% QoQ', source_category: 'Sales', data_age_days: 13 },
      { label: 'Portal visit frequency', value: '3 → 6 visits/mo', source_category: 'Digital', data_age_days: 10 },
      { label: 'PMR survey wave 2026-W2', value: 'Shift to Early adopter', source_category: 'Survey', data_age_days: 8 },
      { label: 'Rep observation (Tomás Ferreira)', value: '4 new patient starts on Aurelix', source_category: 'CRM', data_age_days: 5 },
    ],
    flag_ids: ['DRF-000001'],
    origin: 'Event-driven',
    origin_ref: null,
    approver_role: 'P2',
    approver_user_id: 'USR-002',
    status: 'Proposed',
    hold_reason: null,
    policy_rule_ref: null,
    explanation_key: 'PRP-000001',
    created_at: '2026-10-11T10:00:00Z',
    decided_at: null,
    decided_by: null,
    decision_reason: null,
  },
  {
    proposal_id: 'PRP-000002',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    indication_code: 'AUR_PSO',
    dimension_code: 'BEHAVIOURAL',
    current_value: 'Traditionalist',
    proposed_value: 'Engaged',
    segment_age_days: 164,
    confidence: 'High',
    drivers: [
      { label: 'Brick sales acceleration', value: '+12% QoQ', source_category: 'Sales', data_age_days: 13 },
      { label: 'Digital engagement growth', value: '6 portal sessions/mo', source_category: 'Digital', data_age_days: 10 },
    ],
    flag_ids: ['DRF-000002'],
    origin: 'Event-driven',
    origin_ref: null,
    approver_role: 'P2',
    approver_user_id: 'USR-002',
    status: 'Proposed',
    hold_reason: null,
    policy_rule_ref: null,
    explanation_key: 'PRP-000002',
    created_at: '2026-10-11T10:05:00Z',
    decided_at: null,
    decided_by: null,
    decision_reason: null,
  },
  {
    proposal_id: 'PRP-000003',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    indication_code: 'AUR_PSO',
    dimension_code: 'ATTITUDINAL',
    current_value: 'Late majority',
    proposed_value: 'Early adopter',
    segment_age_days: 164,
    confidence: 'High',
    drivers: [
      { label: 'PMR Wave 2026-W2 response', value: 'Classified as Early Adopter', source_category: 'Survey', data_age_days: 8 },
    ],
    flag_ids: ['DRF-000003'],
    origin: 'Event-driven',
    origin_ref: null,
    approver_role: 'P2',
    approver_user_id: 'USR-002',
    status: 'Proposed',
    hold_reason: null,
    policy_rule_ref: null,
    explanation_key: 'PRP-000003',
    created_at: '2026-10-11T10:10:00Z',
    decided_at: null,
    decided_by: null,
    decision_reason: null,
  },
  {
    proposal_id: 'PRP-000004',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    indication_code: 'AUR_PSO',
    dimension_code: 'DIGITAL',
    current_value: 'Evolving',
    proposed_value: 'Savvy',
    segment_age_days: 164,
    confidence: 'High',
    drivers: [
      { label: 'Monthly portal visits', value: 'Doubled from 3 to 6', source_category: 'Digital', data_age_days: 10 },
      { label: 'Rep note preference', value: 'Expressed clear portal preference', source_category: 'CRM', data_age_days: 5 },
    ],
    flag_ids: ['DRF-000004'],
    origin: 'Event-driven',
    origin_ref: null,
    approver_role: 'P4',
    approver_user_id: 'USR-006',
    status: 'Proposed',
    hold_reason: null,
    policy_rule_ref: null,
    explanation_key: 'PRP-000004',
    created_at: '2026-10-11T10:15:00Z',
    decided_at: null,
    decided_by: null,
    decision_reason: null,
  },
  {
    proposal_id: 'PRP-000005',
    market_code: 'MKT_B',
    customer_type: 'HCP',
    customer_id: 'HCP-B-0001',
    brand_code: 'AUR',
    indication_code: 'AUR_PSO',
    dimension_code: 'ADOPTION',
    current_value: 'Consideration',
    proposed_value: 'Expansion',
    segment_age_days: 164,
    confidence: 'High',
    drivers: [
      { label: 'Patient initiation', value: '4 new moderate-to-severe starts', source_category: 'CRM', data_age_days: 5 },
      { label: 'Brick volume trajectory', value: '+12% QoQ', source_category: 'Sales', data_age_days: 13 },
    ],
    flag_ids: ['DRF-000005'],
    origin: 'Event-driven',
    origin_ref: null,
    approver_role: 'P4',
    approver_user_id: 'USR-006',
    status: 'Proposed',
    hold_reason: null,
    policy_rule_ref: null,
    explanation_key: 'PRP-000005',
    created_at: '2026-10-11T10:20:00Z',
    decided_at: null,
    decided_by: null,
    decision_reason: null,
  },
];
